 Vagrant.configure("2") do |config|
  config.vm.box_check_update = true
  config.vm.define "test" do |machine|
    machine.vm.hostname = "test"
    machine.vm.box = "devboxes/ubuntu-22-04"
    machine.vm.provider "virtualbox" do |vb|
      vb.gui = false
    end
  end
end